name: Lint & Format, and module checks
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.1
          skip-cache: true
          skip-build-cache: true
          args: "--timeout 3m --verbose --out-${NO_FUTURE}format colored-line-number"

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile

      - name: install required tools
        if: env.GIT_DIFF
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: lint & format, and module check
        if: env.GIT_DIFF
        run: make check
