name: Test & Benchmark
on: [push]
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true
          cache-dependency-path: go.sum

      - name: test unit
        run: make test-unit

      - name: test race
        run: make test-race

      - name: test coverage
        run: make test-cover

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true
          cache-dependency-path: go.sum

      - name: benchmark all tests
        run: make benchmark

      # - name: cpu-profile sim-test
      #   run: make cpu-profile-simulation-test
